### ISSUE TITLE
Doesn't find timezone for city and country together

### ISSUE THREAD

**Issue by rotimi-best** [mountainfirefly/country-timezone#1]
```javascript
const countryTimezone = require('country-timezone');
const timezone = countryTimezone.getTimezonesWithCountryName('Lagos Nigeria');
console.log(timezone); // []

const countryTimezone = require('country-timezone');
const timezone = countryTimezone.getTimezonesWithCountryName('Nigeria');
console.log(timezone); // ['Africa/Lagos']
```

I expect it to also find the timezone if a city and country was indicated.

**Comment by mountainfirefly** [comment]
@Rotimi-Best With the country name, it works perfectly. For the city, I will add the handling. Please expect it soon.

**Comment by mountainfirefly** [comment]
@Rotimi-Best It is done and published. Please have look at it and let me know if satisfy your expectations then I'll close this issue.

**Comment by rotimi-best** [comment]
Okay this was solved but when I just use the name of the city without a country it still gives an empty array.

```javascript
const countryTimezone = require("country-timezone");
const timezone = countryTimezone.getTimezonesWithCountryName("Lagos Nigeria");
console.log(timezone); // ['Africa/Lagos']

const countryTimezone = require("country-timezone");
const timezone = countryTimezone.getTimezonesWithCountryName("Lagos");
console.log(timezone); // []
```

**Comment by mountainfirefly** [comment]
@Rotimi-Best I don't have data for cities if you can help me with that then I can add that functionality.

**Comment by rotimi-best** [comment]
Here are some you can look through to see if they fit your need:
- [all-countries-and-cities-json](https://github.com/russ666/all-countries-and-cities-json)
- [cities.json](https://github.com/lutangar/cities.json)
- [free-world-cities-database](https://www.maxmind.com/en/free-world-cities-database)

**Comment by rotimi-best** [comment]
I think any of them would be enough to make it a reality.

**Comment by mountainfirefly** [comment]
Thanks, this is great!
I will do it soon.

**Comment by mountainfirefly** [comment]
@Rotimi-Best It is done. Thank you so much for your help. Please have a look then I'll close this issue.

**Comment by rotimi-best** [comment]
Alright would do after the weekend. Thanks for the improvements.

**Comment by rotimi-best** [comment]
Okay cool it works.
